Message:
  reload: "&a重载成功！"
  successSave: "&a存储队伍成功！"
  quitSuccess: "&a退出无尽试炼塔成功！"
  quitFail: "&c您并没有加入无尽试炼!"
  next: "&a下一场对战开始!"
  noTimes: "&c您的挑战次数不够了!"
Times:
  reset: "0000"
Tower:
  金币试炼:
    #挑战模式：
    # ONLY 一次性挑战
    # ENDLESS 无尽挑战
    mode: "ONLY"
    Times:
      #默认3次
      default: 3
      commands:
        - "broadcast 金币挑战塔挑战次数重置!"
  无尽试炼:
    mode: "ENDLESS"
    Times:
      #默认1次
      default: 1
      commands:
        - "broadcast 精灵无尽挑战塔挑战次数重置!"